spring.application.name=notes-api

# JWT Configuration
app.jwtSecret=notesApiSecretKeyForJWTTokenGenerationAndValidation2024!
app.jwtExpirationMs=86400000

# Security Configuration
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

# Logging Configuration
logging.level.com.rmarcello.note.security=INFO
logging.level.com.rmarcello.note.controller=INFO
logging.level.org.springframework.security=WARN

# Server Configuration
server.port=8080
